image: node:14

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y python3-pip
    - pip3 install awscli
    - aws s3 sync ./build s3://your-bucket-name --delete
  only:
    - main
